FROM registry.access.redhat.com/ubi9-minimal
MAINTAINER Aly Ibrahim<aly.ibrahim@gmail.com>
RUN microdnf update -y
RUN microdnf install java-11-openjdk -y
ADD target/ /opt/app-root/src
RUN microdnf clean all
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "animals-counter-springboot-0.0.1-SNAPSHOT.jar"]
